apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-runner
  namespace: arc-system
spec:
  replicas: 1
  template:
    spec:
      repository: Egor-Dragun/k8s_cicd
      labels:
        - arc
      ephemeral: true
